// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kbHaB3fFCbJTZ4qkWASSJnTZaYiDJXI',
    appId: '1:936637673498:web:a5ec6823824514882ae1a3',
    messagingSenderId: '936637673498',
    projectId: 'mad-hw4-project6565',
    authDomain: 'mad-hw4-project6565.firebaseapp.com',
    storageBucket: 'mad-hw4-project6565.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWo-bWR-D9yv_Ln5r9tJX-tTlvVe1NHAM',
    appId: '1:936637673498:android:fad2dcafad5b7f902ae1a3',
    messagingSenderId: '936637673498',
    projectId: 'mad-hw4-project6565',
    storageBucket: 'mad-hw4-project6565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5AeayWUdjImhl8-hSp_R72zSkXwoUNqk',
    appId: '1:936637673498:ios:8187a6740620f34b2ae1a3',
    messagingSenderId: '936637673498',
    projectId: 'mad-hw4-project6565',
    storageBucket: 'mad-hw4-project6565.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5AeayWUdjImhl8-hSp_R72zSkXwoUNqk',
    appId: '1:936637673498:ios:8187a6740620f34b2ae1a3',
    messagingSenderId: '936637673498',
    projectId: 'mad-hw4-project6565',
    storageBucket: 'mad-hw4-project6565.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-kbHaB3fFCbJTZ4qkWASSJnTZaYiDJXI',
    appId: '1:936637673498:web:c68355b5014defbd2ae1a3',
    messagingSenderId: '936637673498',
    projectId: 'mad-hw4-project6565',
    authDomain: 'mad-hw4-project6565.firebaseapp.com',
    storageBucket: 'mad-hw4-project6565.firebasestorage.app',
  );

}